SELECT [CustomerKey]
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      --,[FirstName]
      --,[MiddleName]
      --,[LastName]
	  , CASE WHEN [MiddleName] IS NOT NULL THEN [FirstName] + ' ' + [MiddleName] + '.' + ' ' + [LastName] ELSE [FirstName] + ' ' + [LastName] END AS FullName
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      --,[Gender]
	  , CASE WHEN [Gender] = 'F' THEN 'Female' WHEN [Gender] ='M' THEN 'Male' END AS Gender
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,[DateFirstPurchase]
      --,[CommuteDistance]
	  ,[City] -- from [AdventureWorksDW2019].[dbo].[DimGeography]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer] AS c
  LEFT JOIN [AdventureWorksDW2019].[dbo].[DimGeography] AS g
  ON c.[GeographyKey] = g.[GeographyKey]